<?php

/**
 * Class IndexController
 */
class IndexController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 网站首页入口
     * @throws \Twig\Error\LoaderError
     * @throws \Twig\Error\RuntimeError
     * @throws \Twig\Error\SyntaxError
     */
    public function indexAction()
    {
        $this->twig->display('index/index.twig', $this->assign);
    }
}
