<?php

/**
 * @name IndexController
 * @author icker
 * @desc 默认控制器
 */


class IndexController extends BaseController
{
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 网站首页入口
     * @throws Yaf_Exception_TypeError
     */
    public function indexAction()
    {
        return $this->twig->display('index/index.twig', $this->assign);
    }
}
